catalog:
  rest_epa:
    type: rest
    uri: http://localhost:8181
    warehouse: s3://warehouse/
    # S3 FileIO configuration for MinIO
    s3.endpoint: http://localhost:9000
    s3.access-key-id: admin
    s3.secret-access-key: password
    s3.path-style-access: true
    s3.region: us-east-1

